---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    ran.openshift.io/ztp-deploy-wave: "2"
spec:
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Manual
status:
  state: AtLatestKnown
