---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "upgrade-4.14"
  namespace: "ztp-upgrade"
  annotations:
    force: "force-again"
spec:
  bindingRules:
    config-version: upgrade-to-4.14
  remediationAction: inform
  sourceFiles:
    - fileName: AdminAcksCM.yaml
      policyName: "admin-ack"
      metadata:
        annotations:
          ran.openshift.io/ztp-deploy-wave: "200"
      data:
        ack-4.13-kube-1.27-api-removals-in-4.14: "true"
    - fileName: ClusterVersion.yaml
      policyName: "ocp-upgrade"
      metadata:
        name: version
        annotations:
          ran.openshift.io/ztp-deploy-wave: "210"
      spec:
        channel: "eus-4.14"
        desiredUpdate:
          version: 4.14.28
      status:
        history:
          - version: 4.14.28
            state: "Completed"
    - fileName: DefaultCatsrc.yaml
      policyName: "catalog-update"
      metadata:
        name: redhat-operators
        annotations:
          ran.openshift.io/ztp-deploy-wave: "220"
      spec:
        displayName: redhat-operators
        image: registry.redhat.io/redhat/redhat-operator-index:v4.14
        updateStrategy:
          registryPoll:
            interval: 5m
    - fileName: Subscription.yaml
      policyName: "odf-upgrade"
      metadata:
        name: odf-operator
        namespace: openshift-storage
        annotations:
          ran.openshift.io/ztp-deploy-wave: "230"
      spec:
        channel: "stable-4.14"
        name: odf-operator
    - fileName: MachineConfigPool.yaml
      policyName: "unpause-mcp"
      metadata:
        annotations:
          ran.openshift.io/ztp-deploy-wave: "240"
        labels:
          machineconfiguration.openshift.io/role: ht
        name: ht
      spec:
        machineConfigSelector:
          matchExpressions:
            - {key: machineconfiguration.openshift.io/role, operator: In, values: [worker,ht]}
        nodeSelector:
          matchLabels:
            node-role.kubernetes.io/ht: ""
        paused: false
    - fileName: MachineConfigPool.yaml
      policyName: "unpause-mcp"
      metadata:
        annotations:
          ran.openshift.io/ztp-deploy-wave: "240"
        labels:
          machineconfiguration.openshift.io/role: std
        name: std
      spec:
        machineConfigSelector:
          matchExpressions:
            - {key: machineconfiguration.openshift.io/role, operator: In, values: [worker,std]}
        nodeSelector:
          matchLabels:
            node-role.kubernetes.io/ht: ""
        paused: false