---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "upgrade-4.14"
  namespace: "ztp-upgrade"
  annotations:
    force: "force-again"
spec:
  bindingRules:
    config-version: upgrade-to-4.14
  remediationAction: inform
  sourceFiles:
    - fileName: AdminAcksCM.yaml
      policyName: "admin-ack"
      metadata:
        annotations:
          ran.openshift.io/ztp-deploy-wave: "200"
      data:
        ack-4.13-kube-1.27-api-removals-in-4.14: "true"
    - fileName: ClusterVersion.yaml
      policyName: "ocp-upgrade"
      metadata:
        name: version
        annotations:
          ran.openshift.io/ztp-deploy-wave: "210"
      spec:
        channel: "eus-4.14"
        desiredUpdate:
          version: 4.14.28
      status:
        history:
          - version: 4.14.28
            state: "Completed"
    - fileName: DefaultCatsrc.yaml
      policyName: "catalog-update"
      metadata:
        name: redhat-operators
        annotations:
          ran.openshift.io/ztp-deploy-wave: "220"
      spec:
        displayName: redhat-operators
        image: registry.redhat.io/redhat/redhat-operator-index:v4.14
        updateStrategy:
          registryPoll:
            interval: 2m
    - fileName: Subscription.yaml
      policyName: "operator-upgrade"
      metadata:
        name: odf-operator
        namespace: openshift-storage
        annotations:
          ran.openshift.io/ztp-deploy-wave: "230"
      spec:
        channel: "stable-4.14"
        name: odf-operator
      status:
        state: AtLatestKnown
    # SRIOV
    - fileName: Subscription.yaml
      policyName: "operator-upgrade"
      metadata:
        name: sriov-network-operator-subscription
        namespace: openshift-sriov-network-operator
        annotations:
          ran.openshift.io/ztp-deploy-wave: "230"
      spec:
        name: sriov-network-operator
        channel: "stable"
      status:
        state: AtLatestKnown
    # LSO
    - fileName: Subscription.yaml
      policyName: "operator-upgrade"
      metadata:
        name: local-storage-operator
        namespace: openshift-local-storage
        annotations:
          ran.openshift.io/ztp-deploy-wave: "230"
      spec:
        channel: "stable"
        name: local-storage-operator
      status:
        state: AtLatestKnown
    # MetalLB
    - fileName: Subscription.yaml
      policyName: "operator-upgrade"
      metadata:
        name: metallb-operator
        namespace: metallb-system
        annotations:
          ran.openshift.io/ztp-deploy-wave: "230"
      spec:
        channel: "stable"
        name: metallb-operator
      status:
        state: AtLatestKnown