---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    ran.openshift.io/ztp-deploy-wave: "2"
  name: openshift-storage-operatorgroup
  namespace: openshift-storage
spec:
  targetNamespaces:
  - openshift-storage
