---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generators:
  - operator-subs.yaml
  - machine-config-pools.yaml
  - cluster-version.yaml
  - odf-config.yaml

resources:
  - cluster-image-set.yaml