---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "operator-subs-4.14"
  namespace: "ztp-common"
spec:
  bindingRules:
    config-version: 4.14
  remediationAction: inform
  sourceFiles:
    - fileName: OperatorHub.yaml
      policyName: "catalog-policy"
    - fileName: DefaultCatsrc.yaml
      policyName: "catalog-policy"
      # The Subscriptions all point to redhat-operators-disconnected. The OperatorHub CR
      # disables the defaults and this CR replaces redhat-operators-disconnected with a
      # CatalogSource pointing to the disconnected registry. Including both of
      # these in the same policy orders their application to the cluster.
      # Tip: for RH sources `image: registry.redhat.io/redhat/redhat-operator-index:v4.xx`
      metadata:
        name: redhat-operators
      spec:
        displayName: redhat-operators
        image: registry.redhat.io/redhat/redhat-operator-index:v4.14
    # SRIOV
    - fileName: SriovSubscriptionNS.yaml
      policyName: "subscription-policy"
    - fileName: SriovSubscriptionOperGroup.yaml
      policyName: "subscription-policy"
    - fileName: Subscription.yaml
      policyName: "subscription-policy"
      metadata:
        name: sriov-network-operator-subscription
        namespace: openshift-sriov-network-operator
      spec:
        name: sriov-network-operator
        channel: "stable"
    # LSO
    - fileName: StorageNS.yaml
      policyName: "subscription-policy"
    - fileName: StorageOperGroup.yaml
      policyName: "subscription-policy"
    - fileName: Subscription.yaml
      policyName: "subscription-policy"
      metadata:
        name: local-storage-operator
        namespace: openshift-local-storage
      spec:
        channel: "stable"
        name: local-storage-operator
    # ODF
    - fileName: OdfNS.yaml
      policyName: "subscription-policy"
    - fileName: OdfOperGroup.yaml
      policyName: "subscription-policy"
    - fileName: Subscription.yaml
      policyName: "subscription-policy"
      metadata:
        name: odf-operator
        namespace: openshift-storage
      spec:
        channel: "stable-4.14"
        name: odf-operator
    # MetalLB
    - fileName: MlbNS.yaml
      policyName: "subscription-policy"
    - fileName: MlbOperGroup.yaml
      policyName: "subscription-policy"
    - fileName: Subscription.yaml
      policyName: "subscription-policy"
      metadata:
        name: metallb-operator
        namespace: metallb-system
      spec:
        channel: "stable"
        name: metallb-operator
